# SPDX-License-Identifier: GPL-3.0-only
# gen_pono_spinner.py - bake a tapered cyan "comet" spinner into an LVGL
# canned-animation frame array (lv_animimg). Pre-rendered frames mean playback
# on the printer is a per-frame bitmap blit (near-zero CPU, no vector math),
# which is what lets a weak 2-core A7 with no GPU show a smooth loader.
#
# Output: assets/pono/anim/pono_spinner.c
#   const lv_img_dsc_t * pono_spinner_frames[N];   // LV_IMG_CF_TRUE_COLOR_ALPHA
#   const uint8_t        pono_spinner_frame_count;
#
# Pixel order is B,G,R,A to match LVGL LV_COLOR_DEPTH=32 (lv_color32_t).
# Regenerate after changing size/frames/color; result is committed.

import os
import numpy as np
from PIL import Image

SIZE = 88          # on-screen px (square)
SS = 3             # supersample for anti-aliasing
N = 24             # frames in one revolution (15 deg/frame -> smooth at 1s)
CYAN = (0, 229, 255)   # color_accent_primary #00e5ff
TAIL_DEG = 290.0   # comet length; the remaining ~70 deg is the transparent gap
Rc = 34.0          # ring centre radius (in on-screen px)
HW = 4.5           # ring half-width at the head (in on-screen px)
EDGE = 1.3         # AA falloff width (in on-screen px)

W = SIZE * SS
cx = cy = W / 2.0
ys, xs = np.mgrid[0:W, 0:W]
dx = xs - cx + 0.5
dy = ys - cy + 0.5
rad = np.hypot(dx, dy)
# phi: degrees CCW from +x, with screen y flipped so +90 deg is the top edge.
phi = (np.degrees(np.arctan2(-dy, dx))) % 360.0


def frame_alpha(head_deg):
    d = (head_deg - phi) % 360.0          # 0 at head, grows clockwise
    ang = np.clip(1.0 - d / TAIL_DEG, 0.0, 1.0)
    ang = np.where(d > TAIL_DEG, 0.0, ang)
    hw_eff = (HW * (0.45 + 0.55 * ang)) * SS   # taper the stroke toward the tail
    band = np.clip((hw_eff - np.abs(rad - Rc * SS)) / (EDGE * SS), 0.0, 1.0)
    return band * ang


def emit_c(frames, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = []
    lines.append('// SPDX-License-Identifier: GPL-3.0-only')
    lines.append('// GENERATED by tools/gen_pono_spinner.py - do not edit by hand.')
    lines.append('// Canned comet spinner frames for lv_animimg (TRUE_COLOR_ALPHA, B,G,R,A).')
    lines.append('#include "lvgl.h"')
    lines.append('')
    n = len(frames)
    for i, img in enumerate(frames):
        a = np.asarray(img)                 # H x W x 4, RGBA
        bgra = a[..., [2, 1, 0, 3]].tobytes()
        lines.append('static const uint8_t spinner_f%02d_map[] = {' % i)
        row = []
        out = []
        for j, b in enumerate(bgra):
            row.append(str(b))
            if len(row) == 64:
                out.append(','.join(row))
                row = []
        if row:
            out.append(','.join(row))
        lines.append(',\n'.join(out) + ',')
        lines.append('};')
        lines.append('const lv_img_dsc_t pono_spinner_f%02d = {' % i)
        lines.append('  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,')
        lines.append('  .header.always_zero = 0,')
        lines.append('  .header.reserved = 0,')
        lines.append('  .header.w = %d,' % SIZE)
        lines.append('  .header.h = %d,' % SIZE)
        lines.append('  .data_size = %d,' % (SIZE * SIZE * 4))
        lines.append('  .data = spinner_f%02d_map,' % i)
        lines.append('};')
        lines.append('')
    refs = ', '.join('&pono_spinner_f%02d' % i for i in range(n))
    lines.append('const lv_img_dsc_t * pono_spinner_frames[%d] = { %s };' % (n, refs))
    lines.append('const uint8_t pono_spinner_frame_count = %d;' % n)
    lines.append('')
    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(lines))
    sz = os.path.getsize(path)
    print('wrote %s (%d frames, %.1f KB source, %d B rodata)' %
          (path, n, sz / 1024.0, n * SIZE * SIZE * 4))


def main():
    frames = []
    for i in range(N):
        head = (90.0 - i * (360.0 / N)) % 360.0
        a = (np.clip(frame_alpha(head), 0, 1) * 255).astype(np.uint8)
        rgba = np.zeros((W, W, 4), np.uint8)
        rgba[..., 0] = CYAN[0]
        rgba[..., 1] = CYAN[1]
        rgba[..., 2] = CYAN[2]
        rgba[..., 3] = a
        img = Image.fromarray(rgba, 'RGBA').resize((SIZE, SIZE), Image.LANCZOS)
        frames.append(img)
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, '..', 'assets', 'pono', 'anim', 'pono_spinner.c')
    emit_c(frames, os.path.normpath(out))


if __name__ == '__main__':
    main()
