# SPDX-License-Identifier: GPL-3.0-only
# gen_pono_flag.py - bake the Hawaii state flag into a single static LVGL image
# (lv_img_dsc_t). Same emit pipeline as gen_pono_beach.py: one opaque BGRA
# bitmap, blitted once -> zero animation, zero CPU, cannot jank. This is the
# boot-screen hero art.
#
# Output: assets/pono/anim/pono_flag.c
#   const lv_img_dsc_t pono_flag;            // the flag, TRUE_COLOR_ALPHA B,G,R,A
#   const uint16_t     pono_flag_w, _h;      // canvas size (placement)
#
# The Hawaii flag: eight horizontal stripes (top->bottom white, red, blue,
# white, red, blue, white, red - one per island) with the British Union Jack
# in the upper-hoist quadrant. Rendered supersampled then LANCZOS-downscaled so
# the saltire diagonals and cross fimbriation stay clean at 192x96.
#
# Eyeball before wiring:  PONO_FLAG_PREVIEW=1 python tools/gen_pono_flag.py
# Regenerate after any geometry change; result is committed.

import os
import numpy as np
from PIL import Image

W = 192            # on-screen flag width  (2:1 = correct Hawaii proportion)
H = 96             # on-screen flag height
SS = 4             # supersample for clean diagonals
Ws, Hs = W * SS, H * SS

# Flag palette, nudged a touch brighter than spec so it reads on the dark UI.
WHITE = np.array([245, 245, 248], np.float32)
RED   = np.array([206,  26,  54], np.float32)
BLUE  = np.array([ 12,  40, 122], np.float32)

# Eight stripes, top -> bottom (one per main island).
STRIPES = [WHITE, RED, BLUE, WHITE, RED, BLUE, WHITE, RED]


def render_union_jack(cw, ch):
    """Union Jack into a cw x ch (2:1) field. Blue base, white St Andrew
    saltire, counterchanged red St Patrick saltire, white-fimbriated red
    St George cross on top."""
    yy, xx = np.mgrid[0:ch, 0:cw].astype(np.float32)
    field = np.empty((ch, cw, 3), np.float32)
    field[:] = BLUE

    def perp_dist(p0, p1):
        dx, dy = p1[0] - p0[0], p1[1] - p0[1]
        L = float(np.hypot(dx, dy))
        nx, ny = -dy / L, dx / L
        return (xx - p0[0]) * nx + (yy - p0[1]) * ny   # signed perpendicular

    d1 = perp_dist((0, 0), (cw, ch))        # main diagonal  TL -> BR
    d2 = perp_dist((0, ch), (cw, 0))        # anti diagonal  BL -> TR

    white_hw = ch * (1.0 / 6.0)             # half-width of the white saltire arm
    red_hw = ch * (1.0 / 15.0)              # half-width of the red saltire arm
    off = white_hw - red_hw                 # push red to one edge of the white

    sal_white = (np.abs(d1) < white_hw) | (np.abs(d2) < white_hw)
    field[sal_white] = WHITE

    # Counterchange: the red hugs opposite edges either side of centre so the
    # saltire pinwheels (the canonical Union Jack look).
    left = xx < cw / 2.0
    red1 = ((np.abs(d1 - off) < red_hw) & ~left) | ((np.abs(d1 + off) < red_hw) & left)
    red2 = ((np.abs(d2 - off) < red_hw) & left) | ((np.abs(d2 + off) < red_hw) & ~left)
    field[(red1 | red2) & sal_white] = RED

    gx_half = ch * 0.10                      # St George arm half-width (1/5 total)
    fimb = ch * (1.0 / 15.0)                 # white fimbriation each side
    vert = np.abs(xx - cw / 2.0)
    horz = np.abs(yy - ch / 2.0)
    field[(vert < gx_half + fimb) | (horz < gx_half + fimb)] = WHITE
    field[(vert < gx_half) | (horz < gx_half)] = RED
    return field


def render_flag():
    img = np.zeros((Hs, Ws, 3), np.float32)
    sh = Hs / 8.0
    for i, col in enumerate(STRIPES):
        y0 = int(round(i * sh))
        y1 = int(round((i + 1) * sh))
        img[y0:y1, :, :] = col
    cw, ch = Ws // 2, Hs // 2               # canton = upper-hoist quadrant
    img[0:ch, 0:cw, :] = render_union_jack(cw, ch)
    out = Image.fromarray(img.astype(np.uint8), 'RGB').resize((W, H), Image.LANCZOS)
    return np.asarray(out)


def emit_c(rgb, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    rgba = np.dstack([rgb, np.full((H, W), 255, np.uint8)])     # opaque
    bgra = rgba[..., [2, 1, 0, 3]].astype(np.uint8).tobytes()
    L = ['// SPDX-License-Identifier: GPL-3.0-only',
         '// GENERATED by tools/gen_pono_flag.py - do not edit by hand.',
         '// Hawaii state flag, static (TRUE_COLOR_ALPHA, B,G,R,A, fully opaque).',
         '#include "lvgl.h"', '']
    L.append('static const uint8_t pono_flag_map[] = {')
    row, out = [], []
    for b in bgra:
        row.append(str(b))
        if len(row) == 64:
            out.append(','.join(row)); row = []
    if row:
        out.append(','.join(row))
    L.append(',\n'.join(out) + ',')
    L.append('};')
    L.append('const lv_img_dsc_t pono_flag = {')
    L.append('  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,')
    L.append('  .header.always_zero = 0, .header.reserved = 0,')
    L.append('  .header.w = %d, .header.h = %d,' % (W, H))
    L.append('  .data_size = %d,' % (W * H * 4))
    L.append('  .data = pono_flag_map,')
    L.append('};')
    L.append('const uint16_t pono_flag_w = %d;' % W)
    L.append('const uint16_t pono_flag_h = %d;' % H)
    L.append('')
    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(L))
    print('wrote %s (%.1f KB source, %d bytes rodata)' %
          (path, os.path.getsize(path) / 1024.0, W * H * 4))


def main():
    rgb = render_flag()
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(os.path.join(here, '..', 'assets', 'pono', 'anim', 'pono_flag.c'))
    emit_c(rgb, out)
    if os.environ.get('PONO_FLAG_PREVIEW'):
        # 4x nearest-neighbour blow-up on a dark card, to eyeball the art.
        bg = Image.new('RGB', (W + 24, H + 24), (16, 20, 28))
        bg.paste(Image.fromarray(rgb, 'RGB'), (12, 12))
        big = bg.resize(((W + 24) * 4, (H + 24) * 4), Image.NEAREST)
        big.save(os.path.join(here, 'flag_preview.png'))
        print('wrote flag_preview.png')


if __name__ == '__main__':
    main()
