// SPDX-License-Identifier: GPL-3.0-only
// pono_theme.cpp - Pono Print design token definitions + LVGL theme provider
//
// Phase A.1 + A.3 of the Pono Print touch UI per
// docs/design/pono-print-phase-a-technical-brief.md.
//
// Tokens are compile-time constants. The theme provider registers an
// lv_theme_t whose apply_cb sets per-widget-type styles using the tokens.
//
// To extend with Phase G theme variants (Mainsail Blue / High-contrast /
// Pono Cyan-on-Black), keep this file as the Westworld Dark canonical and
// add sibling files (e.g. pono_theme_high_contrast.cpp) selected at init time.

#include "pono_theme.h"

namespace pono {

// ---- Color token definitions (hex from spec §1.1) ----
// lv_color_hex() takes a 24-bit RGB.
const lv_color_t color_surface_base     = LV_COLOR_MAKE(0x0a, 0x0e, 0x17);
const lv_color_t color_surface_raised   = LV_COLOR_MAKE(0x0f, 0x15, 0x20);
const lv_color_t color_surface_elevated = LV_COLOR_MAKE(0x14, 0x1c, 0x2b);
const lv_color_t color_accent_primary   = LV_COLOR_MAKE(0x00, 0xe5, 0xff);
const lv_color_t color_accent_secondary = LV_COLOR_MAKE(0x00, 0xff, 0x88);
const lv_color_t color_state_error      = LV_COLOR_MAKE(0xff, 0x3b, 0x5c);
const lv_color_t color_state_warning    = LV_COLOR_MAKE(0xff, 0xb0, 0x20);
const lv_color_t color_state_intel      = LV_COLOR_MAKE(0xb3, 0x88, 0xff);
const lv_color_t color_text_primary     = LV_COLOR_MAKE(0xe8, 0xed, 0xf5);
const lv_color_t color_text_secondary   = LV_COLOR_MAKE(0x88, 0x92, 0xa8);
const lv_color_t color_text_tertiary    = LV_COLOR_MAKE(0x4a, 0x55, 0x68);

// ---- Border alpha tokens ----
const lv_opa_t opa_border_subtle = 15;  // 6%  of 255
const lv_opa_t opa_border_medium = 31;  // 12% of 255
const lv_opa_t opa_border_strong = 51;  // 20% of 255

// ---- Typography tokens ----
// Defined via extern in pono_theme.h; the actual lv_font_t structs are
// generated by lv_font_conv and live in assets/pono/fonts/*.c files.
//
// Each generated .c emits `extern const lv_font_t <basename>;` where the
// symbol name is derived from the output filename minus .c extension. So
// assets/pono/fonts/inter_regular_14.c exports symbol `inter_regular_14`.
// We alias those externs to our spec-aligned token names below.

extern "C" {
    extern const lv_font_t inter_bold_48;
    extern const lv_font_t inter_bold_28;
    extern const lv_font_t inter_bold_20;
    extern const lv_font_t inter_regular_14;
    extern const lv_font_t inter_medium_12;
    extern const lv_font_t inter_medium_10;
    extern const lv_font_t jbm_bold_32;
    extern const lv_font_t jbm_bold_20;
    extern const lv_font_t jbm_regular_14;
}

const lv_font_t *font_display    = &inter_bold_48;
const lv_font_t *font_h1         = &inter_bold_28;
const lv_font_t *font_h2         = &inter_bold_20;
const lv_font_t *font_body       = &inter_regular_14;
const lv_font_t *font_caption    = &inter_medium_12;
const lv_font_t *font_micro      = &inter_medium_10;
const lv_font_t *font_num_large  = &jbm_bold_32;
const lv_font_t *font_num_medium = &jbm_bold_20;
const lv_font_t *font_num_small  = &jbm_regular_14;

// ---- Theme provider ----

namespace {

void apply_cb(lv_theme_t * /*theme*/, lv_obj_t *obj) {
    // Generic baseline: every object gets the surface-base / text-primary /
    // body-font defaults. Per-widget overrides below.
    lv_obj_set_style_bg_color(obj,   color_surface_base,  LV_PART_MAIN);
    lv_obj_set_style_text_color(obj, color_text_primary,  LV_PART_MAIN);
    lv_obj_set_style_text_font(obj,  font_body,           LV_PART_MAIN);

    if (lv_obj_check_type(obj, &lv_btn_class)) {
        lv_obj_set_style_bg_color(obj,    color_accent_primary, LV_PART_MAIN);
        lv_obj_set_style_radius(obj,      radius_sm,            LV_PART_MAIN);
        lv_obj_set_style_pad_hor(obj,     space_md,             LV_PART_MAIN);
        lv_obj_set_style_pad_ver(obj,     space_sm / 2,         LV_PART_MAIN);
        lv_obj_set_style_text_color(obj,  color_surface_base,   LV_PART_MAIN);
        lv_obj_set_style_text_font(obj,   font_micro,           LV_PART_MAIN);
        // Pressed: scale 0.96 + cyan glow (button.press animation §3.3)
        lv_obj_set_style_transform_zoom(obj, 245, LV_STATE_PRESSED);  // ~0.96 of 256
    }
    else if (lv_obj_check_type(obj, &lv_label_class)) {
        // labels inherit text color/font from parent; nothing further
    }
    else if (lv_obj_check_type(obj, &lv_bar_class)) {
        lv_obj_set_style_bg_color(obj,         color_surface_elevated, LV_PART_MAIN);
        lv_obj_set_style_bg_color(obj,         color_accent_primary,   LV_PART_INDICATOR);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_MAIN | LV_PART_INDICATOR);
    }
    else if (lv_obj_check_type(obj, &lv_slider_class)) {
        lv_obj_set_style_bg_color(obj,         color_surface_elevated, LV_PART_MAIN);
        lv_obj_set_style_bg_color(obj,         color_accent_primary,   LV_PART_INDICATOR);
        lv_obj_set_style_bg_color(obj,         color_text_primary,     LV_PART_KNOB);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_MAIN | LV_PART_INDICATOR);
        lv_obj_set_style_radius(obj,           LV_RADIUS_CIRCLE,       LV_PART_KNOB);
    }
    // Add more widget classes as Phase A.4 panel refactor requires them
    // (lv_list, lv_table, lv_msgbox, lv_chart, lv_keyboard).
}

lv_theme_t pono_theme_obj;

} // namespace

void theme_init(lv_disp_t *disp) {
    // Inherit from LVGL default for any widget class we don't override.
    lv_theme_t *parent = lv_theme_default_init(disp,
        color_accent_primary,   // primary
        color_state_intel,      // secondary
        true,                   // dark
        font_body);
    lv_theme_set_parent(&pono_theme_obj, parent);
    lv_theme_set_apply_cb(&pono_theme_obj, apply_cb);
    lv_disp_set_theme(disp, &pono_theme_obj);
}

} // namespace pono
