// SPDX-License-Identifier: GPL-3.0-only
// pono_anim.h - canned (pre-baked) animations for the Pono Print UI.
//
// These play as lv_animimg bitmap flipbooks: each frame is a straight blit to
// the framebuffer, so there is no per-frame vector drawing or compositing. That
// keeps wait-state motion smooth on the Centauri's 2-core ARMv7 with no GPU,
// where a live-drawn spinner would steal CPU that Klipper needs during a print.
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Baked comet-spinner frames (one revolution). TRUE_COLOR_ALPHA, lamp amber.
// Generated by tools/gen_pono_spinner.py.
extern const lv_img_dsc_t *pono_spinner_frames[];
extern const uint8_t pono_spinner_frame_count;

// Hawaii state flag. Generated by tools/gen_pono_flag.py.
// pono_flag: 192x96 static opaque bitmap (home top bar, zoomed).
// pono_flag_boot_frames: 320x160 flying flipbook (the boot screen flag, Jack
// 2026-06-13: a subtle, looping ~60 fps wave). Played by boot_flag_create().
extern const lv_img_dsc_t pono_flag;
extern const uint16_t pono_flag_w;
extern const uint16_t pono_flag_h;
extern const lv_img_dsc_t *pono_flag_boot_frames[];
extern const uint8_t pono_flag_boot_frame_count;
extern const uint16_t pono_flag_boot_w;
extern const uint16_t pono_flag_boot_h;

#ifdef __cplusplus
}  // extern "C"

namespace pono {

// Create a looping comet spinner centred on nothing in particular - caller
// positions it. period_ms is the time for one full revolution (1000 = 1s).
lv_obj_t *spinner_create(lv_obj_t *parent, uint16_t period_ms = 1000);

// Create the flying Hawaii boot flag: a looping lv_animimg over the canned
// wave frames, played at ~60 fps (one loop = frame_count/60 s). Sized
// to the frame; the caller positions it (pono_flag_boot_w / _h).
lv_obj_t *boot_flag_create(lv_obj_t *parent);

// Full-screen "working" overlay: a scrim + the comet spinner + a status line,
// built once on lv_layer_top and reused. Throw it up at the start of any
// blocking wait (homing, filament load, heating) and drop it when done. The
// spinner anim is stopped while hidden, so an idle overlay costs nothing.
//
// CONTRACT: both touch LVGL objects and do NOT self-lock. The caller must hold
// GuppyScreen::lv_lock. Tap/timer handlers already run under it; a ws-thread
// callback (e.g. a gcode_script completion) must take the lock first.
void busy_show(const char *text);
void busy_hide();

// Thin non-modal OMEGA status banner across the top of the cockpit. Unlike the
// busy overlay this is NOT a scrim: it carries the live OMEGA step + grade
// while a test print runs, since the cal overlay is gated to !printing and
// would otherwise hide all OMEGA feedback through Phase B/C. Built once on
// lv_layer_top, shown only during an OMEGA print. Same lv_lock contract as
// busy_show: the caller must hold GuppyScreen::lv_lock.
void omega_status_show(const char *text);
void omega_status_hide();

}  // namespace pono
#endif
