// SPDX-License-Identifier: GPL-3.0-only
// pono_theme.cpp - Pono Print design token definitions + LVGL theme provider
//
// Kukui on glass. Tokens are compile-time constants; the theme
// provider registers an lv_theme_t whose apply_cb sets per-widget-type
// styles using the tokens.
//
// ---- Documented exceptions to the token coverage rule ----
//
// "Zero raw color / font / opacity / black-white literals in src/*_panel.cpp
// outside this file and theme.cpp". The exceptions below are intentional:
//
//   spoolman_panel.cpp L403:
//     lv_color_hex(std::stoul(c.template get<std::string>(), nullptr, 16))
//     User-defined spool color stored as hex string in the Spoolman DB.
//     Runtime parse of user input; cannot tokenize an infinite hex space.
//
//   main_panel.cpp icon recolor + materialdesign_font_40:
//     icon-styling primitives orthogonal to the text/surface theme.
//
//   pono_home.cpp mesh heatmap ramp:
//     color as function (probed Z deviation), documented at heat_color().

#include "pono_theme.h"

namespace pono {

// ---- Color token definitions (Kukui) ----
const lv_color_t color_surface_base     = LV_COLOR_MAKE(0x0d, 0x0b, 0x09);
const lv_color_t color_surface_raised   = LV_COLOR_MAKE(0x11, 0x0f, 0x0c);
const lv_color_t color_surface_elevated = LV_COLOR_MAKE(0x18, 0x15, 0x10);
const lv_color_t color_accent_primary   = LV_COLOR_MAKE(0xe2, 0xa1, 0x3c);
const lv_color_t color_accent_secondary = LV_COLOR_MAKE(0x8f, 0xd6, 0xad);
const lv_color_t color_state_error      = LV_COLOR_MAKE(0xe0, 0x6a, 0x5a);
const lv_color_t color_state_warning    = LV_COLOR_MAKE(0xc9, 0x92, 0x3f);
const lv_color_t color_state_intel      = LV_COLOR_MAKE(0x6f, 0xae, 0x8c);
const lv_color_t color_text_primary     = LV_COLOR_MAKE(0xe8, 0xe2, 0xd6);
const lv_color_t color_text_secondary   = LV_COLOR_MAKE(0x92, 0x8b, 0x7c);
const lv_color_t color_text_tertiary    = LV_COLOR_MAKE(0x6a, 0x64, 0x57);

// ---- Border alpha tokens ----
// Hairlines are ink over the room: 9% rest, 18% defined, 25% emphasized.
const lv_opa_t opa_border_subtle = 23;
const lv_opa_t opa_border_medium = 46;
const lv_opa_t opa_border_strong = 64;

// ---- Typography tokens ----
// The lv_font_t structs are generated by lv_font_conv and live in
// assets/pono/fonts/*.c; each exports `extern const lv_font_t <basename>`.

extern "C" {
    extern const lv_font_t plex_medium_20;
    extern const lv_font_t plex_regular_14;
    extern const lv_font_t plex_medium_12;
    extern const lv_font_t plex_medium_10;
    extern const lv_font_t plex_semibold_32;
    extern const lv_font_t plex_semibold_20;
    extern const lv_font_t serif_regular_40;
    extern const lv_font_t serif_regular_56;
    extern const lv_font_t serif_italic_18;
}

const lv_font_t *font_h2            = &plex_medium_20;
const lv_font_t *font_body          = &plex_regular_14;
const lv_font_t *font_caption       = &plex_medium_12;
const lv_font_t *font_micro         = &plex_medium_10;
const lv_font_t *font_num_large     = &plex_semibold_32;
const lv_font_t *font_num_medium    = &plex_semibold_20;
const lv_font_t *font_num_small     = &plex_regular_14;
const lv_font_t *font_serif_display = &serif_regular_40;
const lv_font_t *font_serif_xl      = &serif_regular_56;
const lv_font_t *font_serif_italic  = &serif_italic_18;

// ---- Theme provider ----

namespace {

void apply_cb(lv_theme_t * /*theme*/, lv_obj_t *obj) {
    // Generic baseline: every object gets the room / ink / body defaults.
    lv_obj_set_style_bg_color(obj,   color_surface_base,  LV_PART_MAIN);
    lv_obj_set_style_text_color(obj, color_text_primary,  LV_PART_MAIN);
    lv_obj_set_style_text_font(obj,  font_body,           LV_PART_MAIN);

    if (lv_obj_check_type(obj, &lv_btn_class)) {
        // Raw lv_btn (the prompt dialog's buttons): lamp fill, dark text.
        lv_obj_set_style_bg_color(obj,    color_accent_primary, LV_PART_MAIN);
        lv_obj_set_style_radius(obj,      radius_sm,            LV_PART_MAIN);
        lv_obj_set_style_pad_hor(obj,     space_md,             LV_PART_MAIN);
        lv_obj_set_style_pad_ver(obj,     space_sm / 2,         LV_PART_MAIN);
        lv_obj_set_style_text_color(obj,  color_surface_base,   LV_PART_MAIN);
        lv_obj_set_style_text_font(obj,   font_caption,         LV_PART_MAIN);
        lv_obj_set_style_transform_zoom(obj, 245, LV_STATE_PRESSED);  // ~0.96 of 256
    }
    else if (lv_obj_check_type(obj, &lv_label_class)) {
        // labels inherit text color/font from parent; nothing further
    }
    else if (lv_obj_check_type(obj, &lv_bar_class)) {
        lv_obj_set_style_bg_color(obj,         color_surface_elevated, LV_PART_MAIN);
        lv_obj_set_style_bg_color(obj,         color_accent_primary,   LV_PART_INDICATOR);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_MAIN | LV_PART_INDICATOR);
    }
    else if (lv_obj_check_type(obj, &lv_slider_class)) {
        lv_obj_set_style_bg_color(obj,         color_surface_elevated, LV_PART_MAIN);
        lv_obj_set_style_bg_color(obj,         color_accent_primary,   LV_PART_INDICATOR);
        lv_obj_set_style_bg_color(obj,         color_text_primary,     LV_PART_KNOB);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_MAIN | LV_PART_INDICATOR);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_KNOB);
    }
}

lv_theme_t pono_theme_obj;

} // namespace

void theme_init(lv_disp_t *disp) {
    // Inherit from LVGL default for any widget class we don't override.
    lv_theme_t *parent = lv_theme_default_init(disp,
        color_accent_primary,   // primary: the lamp
        color_state_intel,      // secondary: dim phosphor
        true,                   // dark
        font_body);
    lv_theme_set_parent(&pono_theme_obj, parent);
    lv_theme_set_apply_cb(&pono_theme_obj, apply_cb);
    lv_disp_set_theme(disp, &pono_theme_obj);
}

// ---- LV_PALETTE_* to Pono token mapping ----
//
// User-configured temp-sensor color stores an int that casts to lv_palette_t.
// Bridge that int to a Kukui token so user configs render with Pono
// coherence instead of LVGL stock palette colors. Cool palette picks land on
// phosphor (instrument), warm picks on the lamp family, reds on alarm.
lv_color_t color_for_palette(lv_palette_t p) {
    switch (p) {
    case LV_PALETTE_RED:          return color_state_error;
    case LV_PALETTE_PINK:         return color_state_error;
    case LV_PALETTE_PURPLE:       return color_state_intel;
    case LV_PALETTE_DEEP_PURPLE:  return color_state_intel;
    case LV_PALETTE_INDIGO:       return color_state_intel;
    case LV_PALETTE_BLUE:         return color_accent_secondary;
    case LV_PALETTE_LIGHT_BLUE:   return color_accent_secondary;
    case LV_PALETTE_CYAN:         return color_accent_secondary;
    case LV_PALETTE_TEAL:         return color_accent_secondary;
    case LV_PALETTE_GREEN:        return color_accent_secondary;
    case LV_PALETTE_LIGHT_GREEN:  return color_accent_secondary;
    case LV_PALETTE_LIME:         return color_accent_secondary;
    case LV_PALETTE_YELLOW:       return color_state_warning;
    case LV_PALETTE_AMBER:        return color_accent_primary;
    case LV_PALETTE_ORANGE:       return color_state_warning;
    case LV_PALETTE_DEEP_ORANGE:  return color_state_warning;
    case LV_PALETTE_BROWN:        return color_text_tertiary;
    case LV_PALETTE_BLUE_GREY:    return color_text_tertiary;
    case LV_PALETTE_GREY:         return color_text_tertiary;
    case LV_PALETTE_NONE:         return color_text_tertiary;
    default:                      return color_text_tertiary;
    }
}

// ---- Panel open animation ----

namespace {
void panel_opa_cb(void *obj, int32_t v) {
    lv_obj_set_style_opa(static_cast<lv_obj_t *>(obj), (lv_opa_t)v, 0);
}
} // namespace

void panel_open(lv_obj_t *obj) {
    if (obj == NULL) return;
    lv_obj_move_foreground(obj);
    lv_anim_del(obj, panel_opa_cb);             // restart cleanly if re-opened
    lv_obj_set_style_opa(obj, LV_OPA_TRANSP, 0);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, obj);
    lv_anim_set_exec_cb(&a, panel_opa_cb);
    lv_anim_set_values(&a, LV_OPA_TRANSP, LV_OPA_COVER);
    lv_anim_set_time(&a, motion_base);          // 200 ms ease-out fade-in
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_start(&a);
}

} // namespace pono
