// SPDX-License-Identifier: GPL-3.0-only
// pono_theme.cpp - Pono Print design token definitions + LVGL theme provider
//
// Phase A.1 + A.3 of the Pono Print touch UI per
// docs/design/pono-print-phase-a-technical-brief.md.
//
// Tokens are compile-time constants. The theme provider registers an
// lv_theme_t whose apply_cb sets per-widget-type styles using the tokens.
//
// To extend with Phase G theme variants (Mainsail Blue / High-contrast /
// Pono Cyan-on-Black), keep this file as the Westworld Dark canonical and
// add sibling files (e.g. pono_theme_high_contrast.cpp) selected at init time.
//
// ---- Documented exceptions to the token coverage rule ----
//
// Phase A.4 closed-out 2026-05-22 with the rule "zero raw color / font /
// opacity / black-white literals in src/*_panel.cpp outside this file and
// theme.cpp". The exceptions below are intentional and not regressions:
//
//   spoolman_panel.cpp L403:
//     lv_color_hex(std::stoul(c.template get<std::string>(), nullptr, 16))
//     User-defined spool color stored as hex string in the Spoolman DB.
//     Runtime parse of user input; cannot tokenize an infinite hex space.
//
//   main_panel.cpp L64-65:
//     lv_style_set_img_recolor_opa(&style, LV_OPA_30);
//     lv_style_set_img_recolor(&style, lv_color_black());
//     Icon recolor overlay for tab button images. Orthogonal to the Pono
//     text/surface theme; the 30% opacity + black recolor are icon-styling
//     primitives. Phase G may introduce pono::opa_icon_recolor +
//     pono::color_icon_recolor tokens if icon variants are needed.
//
//   main_panel.cpp L171:
//     lv_obj_set_style_text_font(tab_btns, &materialdesign_font_40, ...);
//     Material Design icon font for tab button glyphs (HOME / CONSOLE /
//     SETTING / INFO). Separate font family from the Pono Inter +
//     JetBrains Mono text cluster. Phase G may introduce pono::font_icon
//     if icon-font abstraction is needed.

#include "pono_theme.h"

namespace pono {

// ---- Color token definitions (hex from spec §1.1) ----
// lv_color_hex() takes a 24-bit RGB.
const lv_color_t color_surface_base     = LV_COLOR_MAKE(0x0a, 0x0e, 0x17);
const lv_color_t color_surface_raised   = LV_COLOR_MAKE(0x0f, 0x15, 0x20);
const lv_color_t color_surface_elevated = LV_COLOR_MAKE(0x14, 0x1c, 0x2b);
const lv_color_t color_accent_primary   = LV_COLOR_MAKE(0x00, 0xe5, 0xff);
const lv_color_t color_accent_secondary = LV_COLOR_MAKE(0x00, 0xff, 0x88);
const lv_color_t color_state_error      = LV_COLOR_MAKE(0xff, 0x3b, 0x5c);
const lv_color_t color_state_warning    = LV_COLOR_MAKE(0xff, 0xb0, 0x20);
const lv_color_t color_state_intel      = LV_COLOR_MAKE(0xb3, 0x88, 0xff);
const lv_color_t color_text_primary     = LV_COLOR_MAKE(0xe8, 0xed, 0xf5);
const lv_color_t color_text_secondary   = LV_COLOR_MAKE(0x88, 0x92, 0xa8);
const lv_color_t color_text_tertiary    = LV_COLOR_MAKE(0x4a, 0x55, 0x68);

// ---- Border alpha tokens ----
const lv_opa_t opa_border_subtle = 15;  // 6%  of 255
const lv_opa_t opa_border_medium = 31;  // 12% of 255
const lv_opa_t opa_border_strong = 51;  // 20% of 255

// ---- Typography tokens ----
// Defined via extern in pono_theme.h; the actual lv_font_t structs are
// generated by lv_font_conv and live in assets/pono/fonts/*.c files.
//
// Each generated .c emits `extern const lv_font_t <basename>;` where the
// symbol name is derived from the output filename minus .c extension. So
// assets/pono/fonts/inter_regular_14.c exports symbol `inter_regular_14`.
// We alias those externs to our spec-aligned token names below.

extern "C" {
    extern const lv_font_t inter_bold_48;
    extern const lv_font_t inter_bold_28;
    extern const lv_font_t inter_bold_20;
    extern const lv_font_t inter_regular_14;
    extern const lv_font_t inter_medium_12;
    extern const lv_font_t inter_medium_10;
    extern const lv_font_t jbm_bold_32;
    extern const lv_font_t jbm_bold_20;
    extern const lv_font_t jbm_regular_14;
}

const lv_font_t *font_display    = &inter_bold_48;
const lv_font_t *font_h1         = &inter_bold_28;
const lv_font_t *font_h2         = &inter_bold_20;
const lv_font_t *font_body       = &inter_regular_14;
const lv_font_t *font_caption    = &inter_medium_12;
const lv_font_t *font_micro      = &inter_medium_10;
const lv_font_t *font_num_large  = &jbm_bold_32;
const lv_font_t *font_num_medium = &jbm_bold_20;
const lv_font_t *font_num_small  = &jbm_regular_14;

// ---- Theme provider ----

namespace {

void apply_cb(lv_theme_t * /*theme*/, lv_obj_t *obj) {
    // Generic baseline: every object gets the surface-base / text-primary /
    // body-font defaults. Per-widget overrides below.
    lv_obj_set_style_bg_color(obj,   color_surface_base,  LV_PART_MAIN);
    lv_obj_set_style_text_color(obj, color_text_primary,  LV_PART_MAIN);
    lv_obj_set_style_text_font(obj,  font_body,           LV_PART_MAIN);

    if (lv_obj_check_type(obj, &lv_btn_class)) {
        lv_obj_set_style_bg_color(obj,    color_accent_primary, LV_PART_MAIN);
        lv_obj_set_style_radius(obj,      radius_sm,            LV_PART_MAIN);
        lv_obj_set_style_pad_hor(obj,     space_md,             LV_PART_MAIN);
        lv_obj_set_style_pad_ver(obj,     space_sm / 2,         LV_PART_MAIN);
        lv_obj_set_style_text_color(obj,  color_surface_base,   LV_PART_MAIN);
        lv_obj_set_style_text_font(obj,   font_micro,           LV_PART_MAIN);
        // Pressed: scale 0.96 + cyan glow (button.press animation §3.3)
        lv_obj_set_style_transform_zoom(obj, 245, LV_STATE_PRESSED);  // ~0.96 of 256
    }
    else if (lv_obj_check_type(obj, &lv_label_class)) {
        // labels inherit text color/font from parent; nothing further
    }
    else if (lv_obj_check_type(obj, &lv_bar_class)) {
        lv_obj_set_style_bg_color(obj,         color_surface_elevated, LV_PART_MAIN);
        lv_obj_set_style_bg_color(obj,         color_accent_primary,   LV_PART_INDICATOR);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_MAIN | LV_PART_INDICATOR);
    }
    else if (lv_obj_check_type(obj, &lv_slider_class)) {
        lv_obj_set_style_bg_color(obj,         color_surface_elevated, LV_PART_MAIN);
        lv_obj_set_style_bg_color(obj,         color_accent_primary,   LV_PART_INDICATOR);
        lv_obj_set_style_bg_color(obj,         color_text_primary,     LV_PART_KNOB);
        lv_obj_set_style_radius(obj,           radius_sm,              LV_PART_MAIN | LV_PART_INDICATOR);
        lv_obj_set_style_radius(obj,           LV_RADIUS_CIRCLE,       LV_PART_KNOB);
    }
    // Add more widget classes as Phase A.4 panel refactor requires them
    // (lv_list, lv_table, lv_msgbox, lv_chart, lv_keyboard).
}

lv_theme_t pono_theme_obj;

} // namespace

void theme_init(lv_disp_t *disp) {
    // Inherit from LVGL default for any widget class we don't override.
    lv_theme_t *parent = lv_theme_default_init(disp,
        color_accent_primary,   // primary
        color_state_intel,      // secondary
        true,                   // dark
        font_body);
    lv_theme_set_parent(&pono_theme_obj, parent);
    lv_theme_set_apply_cb(&pono_theme_obj, apply_cb);
    lv_disp_set_theme(disp, &pono_theme_obj);
}

// ---- LV_PALETTE_* to Pono token mapping (Phase A.4 pass 6) ----
//
// User-configured temp-sensor color stores an int that casts to lv_palette_t.
// Bridge that int to a Pono Westworld Dark token so user configs render with
// Pono coherence instead of LVGL stock palette colors.
//
// LVGL c6b8068 lv_palette_t enum (lvgl/src/misc/lv_color.h L258-280):
//   0  RED        7  LIGHT_BLUE  14 AMBER       0xff NONE (sentinel)
//   1  PINK       8  CYAN        15 ORANGE
//   2  PURPLE     9  TEAL        16 DEEP_ORANGE
//   3  DEEP_PURPLE 10 GREEN      17 BROWN
//   4  INDIGO     11 LIGHT_GREEN 18 BLUE_GREY
//   5  BLUE       12 LIME        19 GREY
//   6            13 YELLOW
//
// Default case covers LV_PALETTE_NONE + any out-of-range int from corrupted
// config + any future LVGL palette additions: lands on text_tertiary (safe
// greyscale).
lv_color_t color_for_palette(lv_palette_t p) {
    switch (p) {
    case LV_PALETTE_RED:          return color_state_error;
    case LV_PALETTE_PINK:         return color_state_error;
    case LV_PALETTE_PURPLE:       return color_state_intel;
    case LV_PALETTE_DEEP_PURPLE:  return color_state_intel;
    case LV_PALETTE_INDIGO:       return color_state_intel;
    case LV_PALETTE_BLUE:         return color_accent_primary;
    case LV_PALETTE_LIGHT_BLUE:   return color_accent_primary;
    case LV_PALETTE_CYAN:         return color_accent_primary;
    case LV_PALETTE_TEAL:         return color_accent_primary;
    case LV_PALETTE_GREEN:        return color_accent_secondary;
    case LV_PALETTE_LIGHT_GREEN:  return color_accent_secondary;
    case LV_PALETTE_LIME:         return color_accent_secondary;
    case LV_PALETTE_YELLOW:       return color_state_warning;
    case LV_PALETTE_AMBER:        return color_state_warning;
    case LV_PALETTE_ORANGE:       return color_state_warning;
    case LV_PALETTE_DEEP_ORANGE:  return color_state_warning;
    case LV_PALETTE_BROWN:        return color_text_tertiary;
    case LV_PALETTE_BLUE_GREY:    return color_text_tertiary;
    case LV_PALETTE_GREY:         return color_text_tertiary;
    case LV_PALETTE_NONE:         return color_text_tertiary;
    default:                      return color_text_tertiary;
    }
}

// ---- Hawaii ocean tide backdrop (boot delighter) ----
//
// Per the token-coverage rule (Phase A.4), raw color literals are permitted
// inside this file. The ocean-specific teal/foam shades below are local to
// this effect and are intentionally NOT promoted into the 30-token spec.

namespace {

// Drift animation exec callbacks: translate a swell bar. Slow loop +
// ping-pong (set via playback_time) reads as a tide rolling in/out, with no
// per-pixel work -- LVGL only repaints each bar's bounding band.
void swell_x_cb(void *bar, int32_t v) {
    lv_obj_set_style_translate_x(static_cast<lv_obj_t *>(bar), v, 0);
}
void swell_y_cb(void *bar, int32_t v) {
    lv_obj_set_style_translate_y(static_cast<lv_obj_t *>(bar), v, 0);
}

// One translucent swell: a wide, short, fully-rounded bar (a lozenge) that
// overhangs the screen edges so its ends never show, drifting horizontally
// with a gentle vertical bob out of phase.
void make_swell(lv_obj_t *parent, lv_color_t color, lv_opa_t opa,
                lv_coord_t y, lv_coord_t h, uint32_t period, int32_t x_range) {
    lv_obj_t *bar = lv_obj_create(parent);
    lv_obj_remove_style_all(bar);
    lv_obj_clear_flag(bar, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(bar, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_size(bar, lv_pct(140), h);            // overhang both edges
    lv_obj_align(bar, LV_ALIGN_TOP_MID, 0, y);
    lv_obj_set_style_bg_color(bar, color, 0);
    lv_obj_set_style_bg_opa(bar, opa, 0);
    lv_obj_set_style_radius(bar, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_border_width(bar, 0, 0);

    lv_anim_t ax;
    lv_anim_init(&ax);
    lv_anim_set_var(&ax, bar);
    lv_anim_set_exec_cb(&ax, swell_x_cb);
    lv_anim_set_values(&ax, -x_range, x_range);
    lv_anim_set_time(&ax, period);
    lv_anim_set_playback_time(&ax, period);
    lv_anim_set_repeat_count(&ax, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&ax, lv_anim_path_ease_in_out);
    lv_anim_start(&ax);

    lv_anim_t ay;
    lv_anim_init(&ay);
    lv_anim_set_var(&ay, bar);
    lv_anim_set_exec_cb(&ay, swell_y_cb);
    lv_anim_set_values(&ay, -4, 4);
    lv_anim_set_time(&ay, period / 2);
    lv_anim_set_playback_time(&ay, period / 2);
    lv_anim_set_repeat_count(&ay, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&ay, lv_anim_path_ease_in_out);
    lv_anim_start(&ay);
}

} // namespace

void ocean_tide_init(lv_obj_t *parent) {
    if (parent == NULL) return;
    // Ocean depth gradient: deep-navy surface at the crest, tropical teal at
    // the trough.
    lv_obj_set_style_bg_color(parent, color_surface_base, 0);                     // #0a0e17
    lv_obj_set_style_bg_grad_color(parent, LV_COLOR_MAKE(0x06, 0x3a, 0x42), 0);   // deep teal
    lv_obj_set_style_bg_grad_dir(parent, LV_GRAD_DIR_VER, 0);
    lv_obj_set_style_bg_opa(parent, LV_OPA_COVER, 0);

    // Layered parallax tide: a deep shelf, mid teal + cyan swells, a fast thin
    // foam glint for sparkle, a green wash and a slow undertow. More layers at
    // out-of-phase speeds read as a living ocean that flexes the 60fps refresh,
    // while every layer is just a cheap translate of a rounded bar (no per-pixel
    // work). Low opacities keep text on top readable.
    make_swell(parent, LV_COLOR_MAKE(0x05, 0x2c, 0x34), LV_OPA_50, 118, 42, 13000, 28); // deep shelf
    make_swell(parent, LV_COLOR_MAKE(0x0a, 0x6e, 0x7a), LV_OPA_40, 150, 30,  9000, 44); // teal swell
    make_swell(parent, color_accent_primary,            LV_OPA_20, 178, 24,  6500, 64); // cyan crest
    make_swell(parent, LV_COLOR_MAKE(0x9b, 0xf6, 0xff), LV_OPA_30, 196, 10,  4800, 82); // foam glint
    make_swell(parent, color_accent_secondary,          LV_OPA_20, 212, 16, 11000, 34); // green wash
    make_swell(parent, LV_COLOR_MAKE(0x0a, 0x6e, 0x7a), LV_OPA_30, 236, 26, 15000, 26); // slow undertow
}

void ocean_tide_stop(lv_obj_t *parent) {
    if (parent == NULL) return;
    // Halt every child's animations. lv_anim_del is a no-op for children with
    // no animation (e.g. a foreground label), so this is safe + idempotent.
    uint32_t n = lv_obj_get_child_cnt(parent);
    for (uint32_t i = 0; i < n; i++) {
        lv_obj_t *child = lv_obj_get_child(parent, i);
        if (child != NULL) lv_anim_del(child, NULL);
    }
}

// ---- Panel open animation ----

namespace {
void panel_opa_cb(void *obj, int32_t v) {
    lv_obj_set_style_opa(static_cast<lv_obj_t *>(obj), (lv_opa_t)v, 0);
}
} // namespace

void panel_open(lv_obj_t *obj) {
    if (obj == NULL) return;
    lv_obj_move_foreground(obj);
    lv_anim_del(obj, panel_opa_cb);             // restart cleanly if re-opened
    lv_obj_set_style_opa(obj, LV_OPA_TRANSP, 0);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, obj);
    lv_anim_set_exec_cb(&a, panel_opa_cb);
    lv_anim_set_values(&a, LV_OPA_TRANSP, LV_OPA_COVER);
    lv_anim_set_time(&a, motion_base);          // 200 ms ease-out fade-in
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_start(&a);
}

} // namespace pono
