// SPDX-License-Identifier: GPL-3.0-only
// pono_anim.h - canned (pre-baked) animations for the Pono Print UI.
//
// These play as lv_animimg bitmap flipbooks: each frame is a straight blit to
// the framebuffer, so there is no per-frame vector drawing or compositing. That
// keeps wait-state motion smooth on the Centauri's 2-core ARMv7 with no GPU,
// where a live-drawn spinner would steal CPU that Klipper needs during a print.
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Baked comet-spinner frames (one revolution). TRUE_COLOR_ALPHA, brand cyan.
// Generated by tools/gen_pono_spinner.py.
extern const lv_img_dsc_t *pono_spinner_frames[];
extern const uint8_t pono_spinner_frame_count;

#ifdef __cplusplus
}  // extern "C"

namespace pono {

// Create a looping comet spinner centred on nothing in particular - caller
// positions it. period_ms is the time for one full revolution (1000 = 1s).
lv_obj_t *spinner_create(lv_obj_t *parent, uint16_t period_ms = 1000);

// Full-screen "working" overlay: a scrim + the comet spinner + a status line,
// built once on lv_layer_top and reused. Throw it up at the start of any
// blocking wait (homing, filament load, heating) and drop it when done. The
// spinner anim is stopped while hidden, so an idle overlay costs nothing.
void busy_show(const char *text);
void busy_hide();

}  // namespace pono
#endif
